### ISSUE TITLE
Nginx configuration?

### ISSUE THREAD

**Issue by gdarko** [EFTEC/RouteOne#3]
Hello,

Do you have any documentation for nginx?

Thanks

**Comment by jorgecc** [comment]
I there:

I added a change for nginx, I also added to the documentation.

It is exactly the same configuration of laravel with a tiny difference.

Laravel:

`try_files $uri $uri/ /index.php?$query_string;`

RouteOne

`try_files $uri $uri/ /router.php?req=$document_uri&$query_string;
`

router.php or the file that you want to use as route.
